# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # The OS image is built inside an Ubuntu VM.
    config.vm.box = "bento/ubuntu-20.04"

    # The /vagrant directory is used to sync files between the VM and the host.
    config.vm.synced_folder "./", "/vagrant", disabled: false

    # This provisioning step sets up the build environment.
    config.vm.provision "setup-build-env",
        type: "shell",
        :path => "scripts/setup-build-env.sh",
        privileged: false

    # This provisioning step builds the OS image.
    config.vm.provision "build-image",
        type: "shell",
        :path => "scripts/build-image.sh",
        privileged: false,
        env: {
            "PI_HOSTNAME"         => ENV["PI_HOSTNAME"],
            "PI_USERNAME"         => ENV["PI_USERNAME"],
            "AUTHORIZED_KEYS_B64" => ENV["AUTHORIZED_KEYS_B64"],
            "WIFI_PASSWORD"       => ENV["WIFI_PASSWORD"],
            "WIFI_SSID"           => ENV["WIFI_SSID"],
        }
end
